### ISSUE TITLE
reward video ad not loading

### ISSUE THREAD

**Issue by amous4822** [googlesamples/android-ads#10]
I tried this sample app and it's showing " onRewardedVideoAdFailedToLoad " with error code 3. I did not change a single line of code. Just pulled it, ran it in my emulator, then on my phone but no luck in either of them.  any help ?

**Comment by riocallos** [comment]
Any help on this? I am experiencing the exact same thing.

**Comment by amous4822** [comment]
Actually you have to wait for like 2-3 days before it starts accepting your request for ads. I just waited for sometime then it started working on it's own.
