### ISSUE TITLE
Required Internet Permission For Banner Ads

### ISSUE THREAD

**Issue by zawawimanja** [googlesamples/android-ads#11]
<uses-permission android:name="android.permission.INTERNET" />

**Comment by stowy** [comment]
Hi,

Internet permissions are added automatically via the gradle manifest merger.

For help getting started with AdMob, please check out our [Getting Started guide](https://developers.google.com/admob/android/quick-start).

For additional support, please see our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android).
