### ISSUE TITLE
play-services-ads:18.1.0 Breaking on Android 4

### ISSUE THREAD

**Issue by lekeope** [googlesamples/android-ads#15]
The version 18.1.0 of play-services-ads is breaking badly on android 4.

Here's a sample fatal error log

```
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.VerifyError: c/d/b/a/g/a/FJ
        at c.d.b.a.g.a.KJ.f(com.google.android.gms:play-services-ads@@18.1.0:2)
        at c.d.b.a.g.a.Sm.a(com.google.android.gms:play-services-ads@@18.1.0:2)
        at c.d.b.a.g.a.bD.a(com.google.android.gms:play-services-ads@@18.1.0:31)
        at c.d.b.a.g.a.NY.a(com.google.android.gms:play-services-ads-lite@@18.1.0:23)
```

**Comment by stowy** [comment]
Hi, thanks for your query.

For support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

Generally these issues are specifically for issues with the sample apps only, as more in depth support for your specific issues is handled by our support team on the forum.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

If you have a specific issue with a sample app, please provide details including which sample app and specific steps to reproduce the issue.
