### ISSUE TITLE
Is it possible to use admob advanced native ads with StaggeredGridLayoutManager?

### ISSUE THREAD

**Issue by slymnozdmrc** [googlesamples/android-ads#5]
I follow your sample project and i can easily display ads in recyclerview with medium and big type of row. But I have also StaggeredRecyclerView but i cannot display advanced native ads in this format. I can only see white screen as a row in ads area. I think this is size issue but Admob limits me for mimumum width value of 280dp. Is there any way to display advanced native ads in StaggeredRecyclerview row?

**Comment by redbrogdon** [comment]
Do you mean something like what this dev did: [https://www.youtube.com/watch?v=o1BRPx4vO7Y](https://www.youtube.com/watch?v=o1BRPx4vO7Y&t=17m18s)?

If so, I haven't tried implementing it personally, though native advanced is so flexible you should be able to make it work. Try bringing your code to our SDK forum: 

https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android

We've got a team of support engineers who'll be happy to take a look.
