### ISSUE TITLE
Get a publishing unit ID

### ISSUE THREAD

**Issue by HD-AD** [googlesamples/android-ads#6]
I followed the following to implement native advance ads.

- https://support.google.com/admob/answer/7187428?hl=en
- https://developers.google.com/admob/android/native-advanced

Everything is working fine. But, currently I'm using the test unit ID and I can't find any information on how to create a native advance ad in AdMob accept the first link above (Line 6 in that link is not there). The only options that are giving is banner, Interstitial and Rewarded.

So what unit Id should I use when releasing my application?

I have asked groups.google.com and on stackoverflow, with no answers. Here is the link to that 

- https://stackoverflow.com/questions/47693005/adding-native-advance-admob-ad
- https://groups.google.com/forum/#!category-topic/google-admob-ads-sdk/android/h_AUSMQhk48

**Comment by HD-AD** [comment]
OK... After some research I have found that native advance is STILL in beta and only available to a small group of publishers, the VIP's if you will.

With native express discontinued and stop serving ads on 1 March 2018 I would have thought that AdMob would make native advance available to all publishers. Unfortunately that is not the case.

AND.. There is no way of contacting them and no info on when Native Advanced will be made available to all publishers.

So, I'm sorry Google AdMob but I will have to look at other options.. Time is money ;)

**Comment by stowy** [comment]
You are correct that Native Advanced is in limited beta and only available to select publishers. If you are interested in joining you should reach out via your account manager. We do not have an estimated time-frame for the general release of this feature at this time.

**Comment by akhil1605** [comment]
I tried to integrate admob to this sample app, but it doesn't worked as expected. Can anyone help me in integrating admob(both banner and interstitial ad ) with this app ?
