### ISSUE TITLE
the sample named "Native Ads Express RecyclerView Sample" is empty. 

### ISSUE THREAD

**Issue by DesignAndBytes** [googlesamples/android-ads#7]
link: https://github.com/googlesamples/android-ads/tree/master/advanced/NativeExpressRecyclerViewExample

**Comment by redbrogdon** [comment]
It's been replaced by the BannerRecyclerViewExample due to the deprecation of Native Ads Express. It shouldn't still be appearing here, though, so thanks for bringing it to our attention. I'll update our release script.
