### ISSUE TITLE
weird issue when running the lint task

### ISSUE THREAD

**Issue by ktiniatros** [googlesamples/android-ads#9]
I'm getting the following when using `implementation "com.google.android.gms:play-services-ads:15.0.1"`:

> * What went wrong:
Execution failed for task ':app:lint'.
> Could not resolve all artifacts for configuration ':app:myAppDebugUnitTestCompileClasspath'.
   > Failed to transform file 'play-services-gass-15.0.1.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
      > GC overhead limit exceeded

Any ideas what can go wrong here?

**Comment by redbrogdon** [comment]
I'm not sure what's going on here. I recommend reposting this in our support forum:

https://groups.google.com/forum/#!forum/google-admob-ads-sdk

We've got a team of support engineers that can dig in, try to replicate the issue, and see what's going on.
